# Generated by Django 4.2.15 on 2024-08-20 11:02

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_sm", models.CharField(max_length=100)),
                ("title_sm_ar", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to=home.models.image_upload)),
            ],
        ),
    ]
