# Generated by Django 4.2.15 on 2024-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pack", name="description", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="pack", name="description_ar", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="pack",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pack",
            name="title_ar",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
