# Generated by Django 4.2.15 on 2024-08-20 11:02

import about.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img1",
                    models.ImageField(
                        null=True, upload_to=about.models.about_image_upload
                    ),
                ),
                (
                    "img2",
                    models.ImageField(
                        null=True, upload_to=about.models.about_image_upload
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                ("years_of_experince", models.IntegerField(default=0)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("years_of_experince", models.IntegerField(default=0)),
                ("team_members", models.IntegerField(default=0)),
                ("happy_clients", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Team_member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to=about.models.team_image_upload)),
                ("name", models.CharField(max_length=50)),
                ("name_ar", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                ("position_ar", models.CharField(max_length=50)),
                ("facebook", models.CharField(max_length=100, null=True)),
                ("twitter", models.CharField(max_length=100, null=True)),
                ("instagram", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tesimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(upload_to=about.models.testimonials_image_upload),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_ar", models.CharField(max_length=50)),
                ("profession", models.CharField(max_length=100)),
                ("profession_ar", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("comment_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Feature_list_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list",
                        to="about.feature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="About_list_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list",
                        to="about.about",
                    ),
                ),
            ],
        ),
    ]
