# Generated by Django 4.2.15 on 2024-08-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="about", name="years_of_experince",),
        migrations.RemoveField(model_name="fact", name="years_of_experince",),
    ]
